// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wbPXVP18emYyho0lMYWS-jV-5A5k3GI',
    appId: '1:941047431151:web:eef47fa540185abc47001a',
    messagingSenderId: '941047431151',
    projectId: 'shogi-flame',
    authDomain: 'shogi-flame.firebaseapp.com',
    storageBucket: 'shogi-flame.appspot.com',
    measurementId: 'G-Z6Q4TY18GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOFpF4kWlHZ2M_B389StMFgdBMPGsZduw',
    appId: '1:941047431151:android:e477217d2ebe3d4d47001a',
    messagingSenderId: '941047431151',
    projectId: 'shogi-flame',
    storageBucket: 'shogi-flame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbRXdYe0_2pHgYjm00BCH7fwoJ3KI55Hg',
    appId: '1:941047431151:ios:96a41ee987d1d9a347001a',
    messagingSenderId: '941047431151',
    projectId: 'shogi-flame',
    storageBucket: 'shogi-flame.appspot.com',
    iosClientId: '941047431151-vri0otp1omu05qb26ko80a2857q7hr0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.shogiGame',
  );
}
